window.DASHBOARD_DATA = {
  "generated_at": "2026-06-26T10:54:45+10:00",
  "generated_date": "2026-06-26",
  "timezone": "Australia/Melbourne",
  "run_type": "daily",
  "counts": {
    "sources_checked": 21,
    "sources_ok": 5,
    "sources_failed": 1,
    "sources_manual": 15,
    "items_scored": 44,
    "items_material": 37,
    "items_new": 0,
    "items_ignored": 7,
    "newsletter_candidates": 4,
    "standards_tracked": 24
  },
  "current_signals": [
    {
      "id": "26bcb636d6619c8f",
      "title": "CRITICAL ALERT: Active exploitation of cPanel/WHM critical vulnerability",
      "source": "ASD ACSC — Alerts & advisories",
      "source_type": "government",
      "published_date": "2026-05-01",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/active-exploitation-of-cpanel-whm-critical-vulnerability",
      "priority": "High",
      "relevance_score": 4,
      "lens": "ASD",
      "summary": "ASD's ACSC reports active exploitation of a critical cPanel/WHM administration vulnerability (CVE-2026-4194). Patches are available and exposed hosting-management consoles are being targeted.",
      "why_it_matters": "A live test of patch-management discipline — Essential Eight 'patch applications' (ML2/ML3 timeframes) and ISM patching controls. Any client on cPanel-based or reseller hosting has an open exposure window now, not a future risk.",
      "suggested_action": "Alert clients running cPanel/WHM, confirm CVE-2026-4194 is patched, and capture the remediation timeline as Essential Eight / ISM control evidence.",
      "newsletter_candidate": true,
      "tags": [
        "acsc",
        "vulnerability"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "78e47568529ad914",
      "title": "Preparing for a ‘vulnerability patch wave’",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-05-01",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/blogs/prepare-for-vulnerability-patch-wave",
      "priority": "High",
      "relevance_score": 4,
      "lens": "CyberResilience",
      "summary": "UK NCSC warns of an incoming 'patch wave' as years of accumulated technical debt are addressed across products, and urges organisations to build patch-management capacity now.",
      "why_it_matters": "Speaks directly to ISO/IEC 27001 Annex A vulnerability- and change-management controls and Essential Eight patch cadence — useful framing for clients whose patch pipelines cannot absorb surge volumes.",
      "suggested_action": "Review clients' patch-management capacity and SLAs against expected surge volumes and flag where ML2 timeframes are unachievable.",
      "newsletter_candidate": true,
      "tags": [
        "vulnerability",
        "patch"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "d0bc636fd27fbc36",
      "title": "Preparing for severe cyber threat: why leaders must act now",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-04-20",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/blogs/preparing-for-severe-cyber-threat-why-leaders-must-act-now",
      "priority": "High",
      "relevance_score": 4,
      "lens": "CyberResilience",
      "summary": "UK NCSC leadership calls on organisations to build collective cyber resilience ahead of a more severe threat environment.",
      "why_it_matters": "Board-level resilience messaging that maps to ISO/IEC 27001 leadership commitment (Clause 5) and cyber-governance reporting — good material for a board or risk-committee conversation.",
      "suggested_action": "Use as a prompt to brief client boards on resilience posture and ISMS leadership commitments.",
      "newsletter_candidate": true,
      "tags": [
        "threat",
        "resilience"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "e96386b842920f36",
      "title": "HIGH ALERT: Ongoing targeting of online code repositories",
      "source": "ASD ACSC — Alerts & advisories",
      "source_type": "government",
      "published_date": "2025-09-19",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/ongoing-targeting-of-online-code-repositories",
      "priority": "High",
      "relevance_score": 4,
      "lens": "ASD",
      "summary": "ASD's ACSC reports increased targeting of online code repositories, with threat actors scanning for exposed secrets and credentials.",
      "why_it_matters": "Directly relevant to secure-development, secrets-management and supply-chain controls (ISM; ISO/IEC 27001 Annex A 8.x; SSDF) — a common and easily checkable client weakness.",
      "suggested_action": "Advise clients to scan repositories for exposed secrets and enforce secret-management and access controls on their code platforms.",
      "newsletter_candidate": true,
      "tags": [
        "acsc",
        "threat"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "1e995fdeb15ded28",
      "title": "Anthropic’s Fable and the State of AI",
      "source": "Schneier on Security",
      "source_type": "research",
      "published_date": "2026-06-19",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.schneier.com/blog/archives/2026/06/anthropics-fable-and-the-state-of-ai.html",
      "priority": "Medium",
      "relevance_score": 3,
      "lens": "ResponsibleAI",
      "summary": "Per Schneier's commentary, the US government classified Anthropic's newly released Fable model as a controlled munition and applied export controls — a notable escalation in how frontier AI is regulated.",
      "why_it_matters": "Signals AI export-control and dual-use governance entering the assurance picture, relevant to AI procurement, cross-border model use and ISO/IEC 42001 risk context. Treat as commentary — verify the underlying facts before citing.",
      "suggested_action": "Track as a watch item on AI export-control exposure for clients procuring or deploying frontier models; verify specifics before any client use.",
      "newsletter_candidate": false,
      "tags": [
        "generative ai",
        "government"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "e9d757e534f1f0d2",
      "title": "CRITICAL ALERT: Reported widespread credential exposure affecting Fortinet Firewalls and VPN Gateways",
      "source": "ASD ACSC — Alerts & advisories",
      "source_type": "government",
      "published_date": "2026-06-18",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/Reported-widespread-credential-exposure-affecting-Fortinet-Firewalls-and-VPN-Gateways",
      "priority": "Medium",
      "relevance_score": 3,
      "lens": "ASD",
      "summary": "ASD's ACSC reports a malicious campaign and widespread credential exposure affecting Fortinet firewalls and VPN gateways.",
      "why_it_matters": "Edge-device and remote-access compromise is a high-impact ISM and Essential Eight concern (MFA, restrict admin privileges, patching) — directly actionable for clients running Fortinet perimeter kit.",
      "suggested_action": "Have clients on Fortinet edge devices rotate credentials, enforce MFA, patch, and review VPN/admin access logs for signs of compromise.",
      "newsletter_candidate": false,
      "tags": [
        "acsc"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "6c75dee5fc404218",
      "title": "NCSC CEO: Hostile states linked to three-quarters of cyber attacks affecting UK's critical systems",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-06-17",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/news/ncsc-ceo-hostile-states-linked-to-three-quarters-of-cyber-attacks",
      "priority": "Medium",
      "relevance_score": 3,
      "lens": "ASD",
      "summary": "UK NCSC CEO Dr Richard Horne told RUSI's annual lecture that hostile states are linked to roughly three-quarters of cyber attacks on the UK's critical infrastructure.",
      "why_it_matters": "Strong board and newsletter framing on nation-state threat and critical-infrastructure resilience; aligns with SOCI-style obligations and ISO/IEC 27001 risk context for regulated sectors.",
      "suggested_action": "Use as a lead talking point on nation-state risk for critical-infrastructure and regulated clients.",
      "newsletter_candidate": false,
      "tags": [
        "critical infrastructure"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "d1230fe571401997",
      "title": "Software supply chain attacks: check your dependencies",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-06-04",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/blogs/software-supply-chain-attacks-check-your-dependencies",
      "priority": "Medium",
      "relevance_score": 3,
      "lens": "CyberResilience",
      "summary": "UK NCSC warns that attackers are compromising open-source packages and asks defenders to review dependencies to reduce supply-chain risk.",
      "why_it_matters": "Maps to supply-chain and secure-development controls (ISO/IEC 27001 Annex A; SSDF; ISM) — a concrete, evidence-producing control area for clients that build software.",
      "suggested_action": "Advise software clients to inventory and monitor dependencies (SBOM, pinning, provenance) and capture it as supply-chain control evidence.",
      "newsletter_candidate": false,
      "tags": [
        "supply chain"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "395560d6009eee7a",
      "title": "Thinking carefully before adopting agentic AI",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-05-15",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/blogs/thinking-carefully-before-adopting-agentic-ai",
      "priority": "Medium",
      "relevance_score": 3,
      "lens": "ResponsibleAI",
      "summary": "UK NCSC urges caution and maturity — 'walk before you run' — before adopting agentic AI.",
      "why_it_matters": "Directly relevant to responsible AI governance and ISO/IEC 42001 — agentic autonomy raises human-oversight, control and risk-assessment questions clients are beginning to ask.",
      "suggested_action": "Offer clients an agentic-AI readiness and oversight check framed against ISO/IEC 42001 controls before deployment.",
      "newsletter_candidate": false,
      "tags": [
        "agentic"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "1736b123361f4d57",
      "title": "Executive Summary: Defending against China-nexus covert networks of compromised devices",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-04-23",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/news/executive-summary-defending-against-china-nexus-covert-networks-of-compromised-devices",
      "priority": "Medium",
      "relevance_score": 3,
      "lens": "CyberResilience",
      "summary": "International cyber agencies advise organisations to baseline edge-device traffic — especially VPN and remote access — and apply dynamic threat-feed filtering against known covert-network indicators.",
      "why_it_matters": "Actionable edge and network-monitoring guidance tied to ISM and ISO/IEC 27001 monitoring controls; relevant to clients with significant remote-access estates.",
      "suggested_action": "Recommend clients baseline edge/VPN traffic and add covert-network indicator filtering to their monitoring.",
      "newsletter_candidate": false,
      "tags": [
        "threat"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "f20549bc96ecdc16",
      "title": "New cross domain guidance for government, industry and the wider security community",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-04-21",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/blogs/new-cross-domain-guidance-for-government-industry-and-the-wider-security-community",
      "priority": "Medium",
      "relevance_score": 3,
      "lens": "PublicSector",
      "summary": "UK NCSC issued new cross-domain guidance to help government, industry and the wider security community deploy cross-domain technologies more consistently.",
      "why_it_matters": "Relevant to high-assurance and public-sector environments that move data across security domains; a useful reference for government and defence-adjacent clients.",
      "suggested_action": "Flag to public-sector and high-assurance clients evaluating cross-domain solutions.",
      "newsletter_candidate": false,
      "tags": [
        "government"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "b3526f078f3c5a01",
      "title": "The AI shift in cyber risk: why leaders must act now",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-06-22",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/news/the-ai-shift-in-cyber-risk-why-leaders-must-act-now",
      "priority": "Watch",
      "relevance_score": 2,
      "lens": "CyberResilience",
      "summary": "UK NCSC argues that AI is materially shifting cyber risk and that leaders must act now to adapt their defences.",
      "why_it_matters": "Bridges cyber and AI assurance — connects board cyber accountability with AI-era threat acceleration; a strong newsletter lead linking the ISO/IEC 27001 and 42001 narratives.",
      "suggested_action": "Use to frame the AI-and-cyber-risk conversation for boards spanning ISO/IEC 27001 and 42001 programs.",
      "newsletter_candidate": false,
      "tags": [],
      "is_new": false,
      "enriched_by": "pro-plan"
    }
  ],
  "sections": {
    "asd_acsc": [
      {
        "id": "26bcb636d6619c8f",
        "title": "CRITICAL ALERT: Active exploitation of cPanel/WHM critical vulnerability",
        "source": "ASD ACSC — Alerts & advisories",
        "source_type": "government",
        "published_date": "2026-05-01",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/active-exploitation-of-cpanel-whm-critical-vulnerability",
        "priority": "High",
        "relevance_score": 4,
        "lens": "ASD",
        "summary": "ASD's ACSC reports active exploitation of a critical cPanel/WHM administration vulnerability (CVE-2026-4194). Patches are available and exposed hosting-management consoles are being targeted.",
        "why_it_matters": "A live test of patch-management discipline — Essential Eight 'patch applications' (ML2/ML3 timeframes) and ISM patching controls. Any client on cPanel-based or reseller hosting has an open exposure window now, not a future risk.",
        "suggested_action": "Alert clients running cPanel/WHM, confirm CVE-2026-4194 is patched, and capture the remediation timeline as Essential Eight / ISM control evidence.",
        "newsletter_candidate": true,
        "tags": [
          "acsc",
          "vulnerability"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "78e47568529ad914",
        "title": "Preparing for a ‘vulnerability patch wave’",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-05-01",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/prepare-for-vulnerability-patch-wave",
        "priority": "High",
        "relevance_score": 4,
        "lens": "CyberResilience",
        "summary": "UK NCSC warns of an incoming 'patch wave' as years of accumulated technical debt are addressed across products, and urges organisations to build patch-management capacity now.",
        "why_it_matters": "Speaks directly to ISO/IEC 27001 Annex A vulnerability- and change-management controls and Essential Eight patch cadence — useful framing for clients whose patch pipelines cannot absorb surge volumes.",
        "suggested_action": "Review clients' patch-management capacity and SLAs against expected surge volumes and flag where ML2 timeframes are unachievable.",
        "newsletter_candidate": true,
        "tags": [
          "vulnerability",
          "patch"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "d0bc636fd27fbc36",
        "title": "Preparing for severe cyber threat: why leaders must act now",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-20",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/preparing-for-severe-cyber-threat-why-leaders-must-act-now",
        "priority": "High",
        "relevance_score": 4,
        "lens": "CyberResilience",
        "summary": "UK NCSC leadership calls on organisations to build collective cyber resilience ahead of a more severe threat environment.",
        "why_it_matters": "Board-level resilience messaging that maps to ISO/IEC 27001 leadership commitment (Clause 5) and cyber-governance reporting — good material for a board or risk-committee conversation.",
        "suggested_action": "Use as a prompt to brief client boards on resilience posture and ISMS leadership commitments.",
        "newsletter_candidate": true,
        "tags": [
          "threat",
          "resilience"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "e96386b842920f36",
        "title": "HIGH ALERT: Ongoing targeting of online code repositories",
        "source": "ASD ACSC — Alerts & advisories",
        "source_type": "government",
        "published_date": "2025-09-19",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/ongoing-targeting-of-online-code-repositories",
        "priority": "High",
        "relevance_score": 4,
        "lens": "ASD",
        "summary": "ASD's ACSC reports increased targeting of online code repositories, with threat actors scanning for exposed secrets and credentials.",
        "why_it_matters": "Directly relevant to secure-development, secrets-management and supply-chain controls (ISM; ISO/IEC 27001 Annex A 8.x; SSDF) — a common and easily checkable client weakness.",
        "suggested_action": "Advise clients to scan repositories for exposed secrets and enforce secret-management and access controls on their code platforms.",
        "newsletter_candidate": true,
        "tags": [
          "acsc",
          "threat"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "e9d757e534f1f0d2",
        "title": "CRITICAL ALERT: Reported widespread credential exposure affecting Fortinet Firewalls and VPN Gateways",
        "source": "ASD ACSC — Alerts & advisories",
        "source_type": "government",
        "published_date": "2026-06-18",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.cyber.gov.au/about-us/view-all-content/Reported-widespread-credential-exposure-affecting-Fortinet-Firewalls-and-VPN-Gateways",
        "priority": "Medium",
        "relevance_score": 3,
        "lens": "ASD",
        "summary": "ASD's ACSC reports a malicious campaign and widespread credential exposure affecting Fortinet firewalls and VPN gateways.",
        "why_it_matters": "Edge-device and remote-access compromise is a high-impact ISM and Essential Eight concern (MFA, restrict admin privileges, patching) — directly actionable for clients running Fortinet perimeter kit.",
        "suggested_action": "Have clients on Fortinet edge devices rotate credentials, enforce MFA, patch, and review VPN/admin access logs for signs of compromise.",
        "newsletter_candidate": false,
        "tags": [
          "acsc"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "6c75dee5fc404218",
        "title": "NCSC CEO: Hostile states linked to three-quarters of cyber attacks affecting UK's critical systems",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-06-17",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/ncsc-ceo-hostile-states-linked-to-three-quarters-of-cyber-attacks",
        "priority": "Medium",
        "relevance_score": 3,
        "lens": "ASD",
        "summary": "UK NCSC CEO Dr Richard Horne told RUSI's annual lecture that hostile states are linked to roughly three-quarters of cyber attacks on the UK's critical infrastructure.",
        "why_it_matters": "Strong board and newsletter framing on nation-state threat and critical-infrastructure resilience; aligns with SOCI-style obligations and ISO/IEC 27001 risk context for regulated sectors.",
        "suggested_action": "Use as a lead talking point on nation-state risk for critical-infrastructure and regulated clients.",
        "newsletter_candidate": false,
        "tags": [
          "critical infrastructure"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "d1230fe571401997",
        "title": "Software supply chain attacks: check your dependencies",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-06-04",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/software-supply-chain-attacks-check-your-dependencies",
        "priority": "Medium",
        "relevance_score": 3,
        "lens": "CyberResilience",
        "summary": "UK NCSC warns that attackers are compromising open-source packages and asks defenders to review dependencies to reduce supply-chain risk.",
        "why_it_matters": "Maps to supply-chain and secure-development controls (ISO/IEC 27001 Annex A; SSDF; ISM) — a concrete, evidence-producing control area for clients that build software.",
        "suggested_action": "Advise software clients to inventory and monitor dependencies (SBOM, pinning, provenance) and capture it as supply-chain control evidence.",
        "newsletter_candidate": false,
        "tags": [
          "supply chain"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "1736b123361f4d57",
        "title": "Executive Summary: Defending against China-nexus covert networks of compromised devices",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-23",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/executive-summary-defending-against-china-nexus-covert-networks-of-compromised-devices",
        "priority": "Medium",
        "relevance_score": 3,
        "lens": "CyberResilience",
        "summary": "International cyber agencies advise organisations to baseline edge-device traffic — especially VPN and remote access — and apply dynamic threat-feed filtering against known covert-network indicators.",
        "why_it_matters": "Actionable edge and network-monitoring guidance tied to ISM and ISO/IEC 27001 monitoring controls; relevant to clients with significant remote-access estates.",
        "suggested_action": "Recommend clients baseline edge/VPN traffic and add covert-network indicator filtering to their monitoring.",
        "newsletter_candidate": false,
        "tags": [
          "threat"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "b3526f078f3c5a01",
        "title": "The AI shift in cyber risk: why leaders must act now",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-06-22",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/the-ai-shift-in-cyber-risk-why-leaders-must-act-now",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "UK NCSC argues that AI is materially shifting cyber risk and that leaders must act now to adapt their defences.",
        "why_it_matters": "Bridges cyber and AI assurance — connects board cyber accountability with AI-era threat acceleration; a strong newsletter lead linking the ISO/IEC 27001 and 42001 narratives.",
        "suggested_action": "Use to frame the AI-and-cyber-risk conversation for boards spanning ISO/IEC 27001 and 42001 programs.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "8e875ec5110fcaba",
        "title": "Alert: NCSC issues advice following global targeting of Fortinet firewalls and VPN gateways",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-06-18",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/advice-following-global-targeting-of-fortinet-firewalls-and-vpn-gateways",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Organisations using Fortinet services are being urged to take action following a campaign affecting firewalls and VPN gateways.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "c6f2968cc3cb337f",
        "title": "The 'vibe coding spectrum' approach to AI-assisted software development",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-06-18",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/the-vibe-coding-spectrum-approach-to-ai-assisted-software-development",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Different code deserves different levels of oversight, so calibrate your approach to ‘vibe coding’ accordingly.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "619dd774b9976035",
        "title": "Designing secure access with ZTNA",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-05-27",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/designing-secure-access-with-ztna",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "New guidance explains how to design Zero Trust Network Access architectures aligned with zero trust principles and not built on old trust assumptions.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "a34e5bfa96fafa05",
        "title": "10 questions to ask when using AI models to find vulnerabilities",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-05-11",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/10-questions-ask-using-ai-models-find-vulnerabilities",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Using Artificial Intelligence to find vulnerabilities can bring added security considerations.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "dbc0e3f164b2e239",
        "title": "Could your choice of metrics be harming your SOC?",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-27",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/could-your-choice-of-metrics-be-harming-your-soc",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Poor metrics can render a well-intentioned security operation centre entirely ineffective.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "5419f3a314e214b7",
        "title": "HIGH ALERT: New steps for organisations running Cisco Firepower and Secure Firewall products",
        "source": "ASD ACSC — Alerts & advisories",
        "source_type": "government",
        "published_date": "2026-04-24",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/new-steps-for-organisations-running-cisco-firepower-and-secure-firewall-products",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "ASD",
        "summary": "ASD partners CISA and NCSC have identified new malware affecting Cisco Firepower and Secure Firewall products.",
        "why_it_matters": "Bears on ASD/ACSC expectations (ISM, Essential Eight); check the impact on baseline controls and audit evidence.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "430b2b4ae76bc199",
        "title": "Passkeys are more secure than traditional ways to log in",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-23",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/passkeys-are-more-secure-than-traditional-ways-to-log-in",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Passkeys offer a more usable, secure replacement for passwords and are already supported by most modern devices.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "74043fb374ce90f7",
        "title": "NCSC: Leave passwords in the past - passkeys are the future",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-23",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/ncsc-leave-passwords-in-the-past-passkeys-are-the-future",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Passkeys are the more secure and user-friendly login method and should be the default authentication option for consumers.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "b4d2cddf82eb0fe3",
        "title": "International cyber agencies share fresh advice to defend against China-linked covert networks",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-23",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/international-cyber-agencies-fresh-advice-defend-against-china-linked-covert-networks",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "New advisory highlights how to defend against attacker tactics believed to be used by China-linked actors to hide malicious cyber activity.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "f3d20af9d2daee2f",
        "title": "Supporting AI adoption for UK cyber defence",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-23",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/supporting-ai-adoption-for-uk-cyber-defence",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Adopting AI will require time, the development of new capabilities and careful oversight.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "7a367612debf8e2a",
        "title": "Defending against China-nexus covert networks of compromised devices",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-23",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/defending-against-china-nexus-covert-networks-of-compromised-devices",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "Explaining the widespread shift in tactics, techniques and procedures (TTPs) towards networks of compromised infrastructure, and how to defend against it",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "3c6f9659ebd97f53",
        "title": "World-first NCSC-engineered device secures vulnerable display links",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-22",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/world-first-ncsc-engineered-device-secures-vulnerable-display-links",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "SilentGlass, a plug-and-play device, actively blocks any unexpected or malicious HDMI and Display Port connections.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "13b8f39d41e90cc0",
        "title": "Cyber chief: UK faces \"perfect storm\" for cyber security",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-21",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/news/cyber-chief-uk-faces-perfect-storm-for-cyber-security",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "CyberResilience",
        "summary": "As the technology landscape develops, the definition of cyber security is expanding with it.",
        "why_it_matters": "Affects cyber-resilience posture; weigh against attack-surface, patching, IAM and incident-response controls.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      }
    ],
    "sc27": [],
    "sc42": [
      {
        "id": "1e995fdeb15ded28",
        "title": "Anthropic’s Fable and the State of AI",
        "source": "Schneier on Security",
        "source_type": "research",
        "published_date": "2026-06-19",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.schneier.com/blog/archives/2026/06/anthropics-fable-and-the-state-of-ai.html",
        "priority": "Medium",
        "relevance_score": 3,
        "lens": "ResponsibleAI",
        "summary": "Per Schneier's commentary, the US government classified Anthropic's newly released Fable model as a controlled munition and applied export controls — a notable escalation in how frontier AI is regulated.",
        "why_it_matters": "Signals AI export-control and dual-use governance entering the assurance picture, relevant to AI procurement, cross-border model use and ISO/IEC 42001 risk context. Treat as commentary — verify the underlying facts before citing.",
        "suggested_action": "Track as a watch item on AI export-control exposure for clients procuring or deploying frontier models; verify specifics before any client use.",
        "newsletter_candidate": false,
        "tags": [
          "generative ai",
          "government"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "395560d6009eee7a",
        "title": "Thinking carefully before adopting agentic AI",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-05-15",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/thinking-carefully-before-adopting-agentic-ai",
        "priority": "Medium",
        "relevance_score": 3,
        "lens": "ResponsibleAI",
        "summary": "UK NCSC urges caution and maturity — 'walk before you run' — before adopting agentic AI.",
        "why_it_matters": "Directly relevant to responsible AI governance and ISO/IEC 42001 — agentic autonomy raises human-oversight, control and risk-assessment questions clients are beginning to ask.",
        "suggested_action": "Offer clients an agentic-AI readiness and oversight check framed against ISO/IEC 42001 controls before deployment.",
        "newsletter_candidate": false,
        "tags": [
          "agentic"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      }
    ],
    "au_gov_ai": [
      {
        "id": "f20549bc96ecdc16",
        "title": "New cross domain guidance for government, industry and the wider security community",
        "source": "UK NCSC — All updates",
        "source_type": "government",
        "published_date": "2026-04-21",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.ncsc.gov.uk/blogs/new-cross-domain-guidance-for-government-industry-and-the-wider-security-community",
        "priority": "Medium",
        "relevance_score": 3,
        "lens": "PublicSector",
        "summary": "UK NCSC issued new cross-domain guidance to help government, industry and the wider security community deploy cross-domain technologies more consistently.",
        "why_it_matters": "Relevant to high-assurance and public-sector environments that move data across security domains; a useful reference for government and defence-adjacent clients.",
        "suggested_action": "Flag to public-sector and high-assurance clients evaluating cross-domain solutions.",
        "newsletter_candidate": false,
        "tags": [
          "government"
        ],
        "is_new": false,
        "enriched_by": "pro-plan"
      },
      {
        "id": "327fdbfc07b8c48c",
        "title": "AI Use by the US Government",
        "source": "Schneier on Security",
        "source_type": "research",
        "published_date": "2026-06-17",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.schneier.com/blog/archives/2026/06/ai-use-by-the-us-government.html",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "PublicSector",
        "summary": "On 14 April, the Trump administration quietly acknowledged the widespread use of AI to automate government processes. The office of management and budget (OMB) disclosed a staggering 3,611 active or planned use cases for AI across the federal government. The list has ballooned by 70% from the one published in the final year of the Biden administration, and includes many disturbing-seeming plans…",
        "why_it_matters": "Australian public sector AI assurance relevance; check DTA standards, AI impact assessment and procurement.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [
          "government"
        ],
        "is_new": false,
        "enriched_by": "deterministic"
      }
    ],
    "regulatory": [
      {
        "id": "049c8ea23448cce1",
        "title": "Quarterly Superannuation Product Statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-06-22",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-superannuation-product-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly Superannuation Product Statistics Superannuation Published 22 June 2026 Print On this page On this page APRA publishes statistics on the superannuation products on a quarterly basis. The Quarterly Superannuation Product Statistics (QSPS) leverages new reporting standards implemented in Phase 1 of the Superannuation Data Transformation project to…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "7149933a07e4fd46",
        "title": "Quarterly Fund-Level Statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-06-22",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-fund-level-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly Fund-Level Statistics Superannuation Published 22 June 2026 Print On this page On this page APRA publishes statistics on superannuation funds on a quarterly basis. In June 2024 APRA released the inaugural quarterly fund-level statistics. The third in a suite of new publications which leverage new reporting standards implemented in Phase 1 of the…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "2c7f806049783451",
        "title": "Quarterly Superannuation Industry publication",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-06-22",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-superannuation-industry-publication",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly Superannuation Industry publication Superannuation Published 22 June 2026 Print On this page On this page The Quarterly Superannuation Industry Publication (QSIP) contains data on superannuation products, investment options, member demographics and investments. Quarterly Superannuation Industry Publication - March 2026 XLSX 416.78 KB ‧ 22 June…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "ad8704866c5f4a17",
        "title": "Professional Athletes and Wearables",
        "source": "Schneier on Security",
        "source_type": "research",
        "published_date": "2026-06-22",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.schneier.com/blog/archives/2026/06/professional-athletes-and-wearables.html",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Privacy",
        "summary": "I haven’t thought about the privacy issues surrounding professional athletes and wearables. Wearables present serious privacy issues for “Average Joe” consumers, who are entrusting tech companies to safely store and protect their biometric data. Imagine the stakes for a professional athlete, whose entire livelihood could be affected by a single biometric data point. To give one of many realistic…",
        "why_it_matters": "Privacy / data-protection relevance; weigh against ISO/IEC 27701, Privacy Act reform and customer assurance.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [
          "privacy"
        ],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "82ddfcc8f5334bc2",
        "title": "Quarterly private health insurance performance statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-05-29",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-private-health-insurance-performance-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly private health insurance performance statistics Private health insurance Published 29 May 2026 Print On this page On this page APRA publishes statistics on the private health insurance industry on a quarterly basis. The industry performance statistics contain aggregate summaries of financial performance and position and capital adequacy. View the…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "abf32211a4ca1d15",
        "title": "Quarterly life insurance performance statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-05-29",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-life-insurance-performance-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly life insurance performance statistics Life insurance Published 29 May 2026 Print On this page On this page APRA publishes statistics on the performance of the life insurance industry on a quarterly basis. These statistics contain industry aggregate summaries of financial performance and position, capital adequacy, as well as details on the…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "125b04a81133445d",
        "title": "Quarterly general insurance performance statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-05-29",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-general-insurance-performance-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly general insurance performance statistics General insurance Published 29 May 2026 Print On this page On this page APRA publishes statistics on the general insurance industry on a quarterly basis. The industry performance statistics contain aggregate summaries of financial performance and position, investments and capital adequacy. Statistics are…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "9c2dfefe34efdb90",
        "title": "Quarterly private health insurance statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-05-29",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-private-health-insurance-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly private health insurance statistics Private health insurance Published 29 May 2026 Print APRA publishes statistics on the private health insurance industry (PHI) on a quarterly basis. The statistics cover the areas of membership, coverage, benefits paid, medical gap, medical devices or human tissue products, and medical services. Quarterly private…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "3a15d74ca7828779",
        "title": "Monthly Authorised Deposit-taking Institution Statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-05-29",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/monthly-authorised-deposit-taking-institution-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Monthly Authorised Deposit-taking Institution Statistics Banking Published 29 May 2026 Print On this page On this page The Monthly Authorised Deposit-taking Institution Statistics (MADIS) publication provides selected information on the banking business of individual banks within the domestic market. Monthly authorised deposit-taking institution statistics…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "ec85bef7dd58a151",
        "title": "Quarterly superannuation statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-05-28",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/quarterly-superannuation-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Quarterly superannuation statistics Superannuation Published 28 May 2026 Print On this page On this page APRA publishes statistics on the superannuation industry on a quarterly basis. The industry performance statistics contains aggregate summaries of financial performance and position, asset allocation and key performance ratios. Statistics relating to…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      },
      {
        "id": "66f1b08410ca4e21",
        "title": "Life insurance claims and disputes statistics",
        "source": "APRA — News & publications",
        "source_type": "regulator",
        "published_date": "2026-04-29",
        "retrieved_at": "2026-06-26T10:53:29+10:00",
        "url": "https://www.apra.gov.au/news-and-publications/life-insurance-claims-and-disputes-statistics",
        "priority": "Watch",
        "relevance_score": 2,
        "lens": "Regulation",
        "summary": "Breadcrumb Home Statistical Publication Life insurance claims and disputes statistics Life insurance Published 29 April 2026 Print On this page On this page APRA publishes life insurance claims and disputes statistics on a biannual basis. These statistics contains industry and insurer-level data on life insurance claims and disputes, and a selection of the published data is also made available in…",
        "why_it_matters": "Regulatory / operational-resilience signal; assess obligations, CPS 230/234 alignment and board reporting.",
        "suggested_action": "Review the source and decide whether it changes advisory positioning, control design or client guidance.",
        "newsletter_candidate": false,
        "tags": [],
        "is_new": false,
        "enriched_by": "deterministic"
      }
    ]
  },
  "section_titles": {
    "asd_acsc": "ASD / ACSC radar",
    "sc27": "SC 27 / 27000 family radar",
    "sc42": "SC 42 / 42000 & AI assurance radar",
    "au_gov_ai": "Australian Government AI assurance",
    "regulatory": "Regulatory & sector watch"
  },
  "standards": {
    "sc27": [
      {
        "designation": "ISO/IEC 27001:2022 + Amd 1:2024",
        "area": "ISMS requirements",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/27001",
        "why": "Core assurance anchor; the climate-action amendment is useful context for integrated management systems."
      },
      {
        "designation": "ISO/IEC 27002:2022",
        "area": "Information security controls",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/75652.html",
        "why": "Control library for ISO 27001 Annex A interpretation, policy rationalisation and audit evidence."
      },
      {
        "designation": "ISO/IEC 27005:2022",
        "area": "Information security risk management",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/80585.html",
        "why": "Risk-process bridge between the ISMS, cyber resilience, supplier risk and AI-enabled system risk."
      },
      {
        "designation": "ISO/IEC 27006-1:2024",
        "area": "ISMS certification bodies",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/82908.html",
        "why": "Important for certification integrity, audit bodies and assurance-market commentary."
      },
      {
        "designation": "ISO/IEC 27017",
        "area": "Cloud information security controls",
        "status": "Under development (revision)",
        "status_class": "dev",
        "url": "https://www.iso.org/standard/43757.html",
        "why": "Watch for alignment to current cloud, SaaS, shared-responsibility and sovereign-cloud assurance."
      },
      {
        "designation": "ISO/IEC 27018:2025",
        "area": "PII protection in public clouds",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/76559.html",
        "why": "Useful for SaaS privacy, processor obligations and customer assurance packs."
      },
      {
        "designation": "ISO/IEC 27701:2025",
        "area": "Privacy information management systems",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/85819.html",
        "why": "Bridge between the ISMS, privacy, Australian Privacy Act reform and AI data governance."
      },
      {
        "designation": "ISO/IEC 27565:2026",
        "area": "Privacy preservation / zero-knowledge proofs",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/committee/45306.html",
        "why": "Niche but relevant to PETs, digital identity, verifiable credentials and sensitive AI use cases."
      },
      {
        "designation": "ISO/IEC 15408 series:2026",
        "area": "IT security evaluation / Common Criteria",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/72891.html",
        "why": "Not 27000, but SC 27-relevant for formal product/security assurance conversations."
      }
    ],
    "sc42": [
      {
        "designation": "ISO/IEC 42001:2023",
        "area": "AI management system",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/81230.html",
        "why": "Anchor for responsible AI governance, internal audit, management review and continual improvement."
      },
      {
        "designation": "ISO/IEC AWI 42003",
        "area": "Implementation guidance for 42001",
        "status": "Under development",
        "status_class": "dev",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Potentially important for practical AIMS implementation playbooks."
      },
      {
        "designation": "ISO/IEC 42005:2025",
        "area": "AI system impact assessment",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/44545.html",
        "why": "Maps directly to use-case triage, impact assessment, benefits/harms and risk evidence."
      },
      {
        "designation": "ISO/IEC 42006:2025",
        "area": "AIMS audit and certification bodies",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/standard/44546.html",
        "why": "Turns AI management systems into a certification and assessor-competence conversation."
      },
      {
        "designation": "ISO/IEC DIS 42007",
        "area": "AI conformity assessment schemes",
        "status": "Under development",
        "status_class": "dev",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Watch closely; may shape AI assurance market models beyond management-system certification."
      },
      {
        "designation": "ISO/IEC TS 42119-2:2025",
        "area": "Testing of AI systems",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Relevant to model/system validation, AI testing, QA, safety, robustness and assurance evidence."
      },
      {
        "designation": "ISO/IEC DTS 42119-3.2",
        "area": "Verification and validation analysis",
        "status": "Under development",
        "status_class": "dev",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Likely high value for model assurance and AI lifecycle testing once published."
      },
      {
        "designation": "ISO/IEC 5259-5:2025",
        "area": "Data quality governance",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Useful for AI data governance, training-data quality and auditability."
      },
      {
        "designation": "ISO/IEC TR 5259-6:2026",
        "area": "Data quality visualisation",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Useful but niche; score higher where AI data observability or reporting is in scope."
      },
      {
        "designation": "ISO/IEC 12792:2025",
        "area": "Transparency taxonomy of AI systems",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Relevant to explainability, transparency statements, public-sector AI and user-facing disclosure."
      },
      {
        "designation": "ISO/IEC TS 6254:2025",
        "area": "Explainability and interpretability",
        "status": "Published",
        "status_class": "published",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Useful for responsible AI control design and assurance language."
      },
      {
        "designation": "ISO/IEC FDIS 42105",
        "area": "Human oversight of AI systems",
        "status": "Under development",
        "status_class": "dev",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "High newsletter value; aligns with public-sector responsible AI and EU-style control expectations."
      },
      {
        "designation": "ISO/IEC CD TS 25568",
        "area": "Generative AI system risk guidance",
        "status": "Under development",
        "status_class": "dev",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Track for agentic AI, public LLMs, prompt injection, model governance and procurement advice."
      },
      {
        "designation": "ISO/IEC AWI 25870",
        "area": "AI incident reporting data elements",
        "status": "Under development",
        "status_class": "dev",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Connects AI governance with incident, breach, safety and regulator reporting."
      },
      {
        "designation": "ISO/IEC AWI TS 25864",
        "area": "AI system resilience assessment",
        "status": "Under development",
        "status_class": "dev",
        "url": "https://www.iso.org/committee/6794475.html",
        "why": "Useful for model/system resilience and assurance framing alongside cyber resilience."
      }
    ]
  },
  "source_queue": [
    {
      "family": "ASD / ACSC",
      "terms": "ISM, Essential Eight, AI, secure by design, critical infrastructure, posture report, alerts",
      "priority": "High"
    },
    {
      "family": "ISO / SC 27",
      "terms": "27000 family, 27001, 27002, 27005, 27006, 27017, 27018, 27701, 275xx privacy, 15408",
      "priority": "High"
    },
    {
      "family": "ISO / SC 42",
      "terms": "42001, 42003, 42005, 42006, 42007, 421xx, 5259, 12792, 25568, 25864, 25870",
      "priority": "High"
    },
    {
      "family": "DTA / digital.gov.au",
      "terms": "AI technical standard, AI impact assessment tool, agentic AI addendum, AI transparency statements",
      "priority": "High"
    },
    {
      "family": "OAIC / privacy",
      "terms": "AI privacy, automated decisions, privacy reform, data breach, APP guidance",
      "priority": "Medium"
    },
    {
      "family": "APRA / ASIC / ACCC",
      "terms": "operational risk, CPS 230/234, AI governance, cyber resilience, enforcement",
      "priority": "Medium"
    },
    {
      "family": "NIST / CISA / ENISA / UK NCSC",
      "terms": "AI RMF, SSDF, KEV, AI cyber, secure AI, resilience, vulnerability exploitation",
      "priority": "Medium"
    }
  ],
  "newsletter_theme": "ASD / ACSC cyber assurance expectations",
  "action_queue": [
    {
      "item_id": "26bcb636d6619c8f",
      "title": "CRITICAL ALERT: Active exploitation of cPanel/WHM critical vulnerability",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/active-exploitation-of-cpanel-whm-critical-vulnerability",
      "priority": "High",
      "action": "Alert clients running cPanel/WHM, confirm CVE-2026-4194 is patched, and capture the remediation timeline as Essential Eight / ISM control evidence."
    },
    {
      "item_id": "78e47568529ad914",
      "title": "Preparing for a ‘vulnerability patch wave’",
      "url": "https://www.ncsc.gov.uk/blogs/prepare-for-vulnerability-patch-wave",
      "priority": "High",
      "action": "Review clients' patch-management capacity and SLAs against expected surge volumes and flag where ML2 timeframes are unachievable."
    },
    {
      "item_id": "d0bc636fd27fbc36",
      "title": "Preparing for severe cyber threat: why leaders must act now",
      "url": "https://www.ncsc.gov.uk/blogs/preparing-for-severe-cyber-threat-why-leaders-must-act-now",
      "priority": "High",
      "action": "Use as a prompt to brief client boards on resilience posture and ISMS leadership commitments."
    },
    {
      "item_id": "e96386b842920f36",
      "title": "HIGH ALERT: Ongoing targeting of online code repositories",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/ongoing-targeting-of-online-code-repositories",
      "priority": "High",
      "action": "Advise clients to scan repositories for exposed secrets and enforce secret-management and access controls on their code platforms."
    },
    {
      "item_id": "1e995fdeb15ded28",
      "title": "Anthropic’s Fable and the State of AI",
      "url": "https://www.schneier.com/blog/archives/2026/06/anthropics-fable-and-the-state-of-ai.html",
      "priority": "Medium",
      "action": "Track as a watch item on AI export-control exposure for clients procuring or deploying frontier models; verify specifics before any client use."
    },
    {
      "item_id": "e9d757e534f1f0d2",
      "title": "CRITICAL ALERT: Reported widespread credential exposure affecting Fortinet Firewalls and VPN Gateways",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/Reported-widespread-credential-exposure-affecting-Fortinet-Firewalls-and-VPN-Gateways",
      "priority": "Medium",
      "action": "Have clients on Fortinet edge devices rotate credentials, enforce MFA, patch, and review VPN/admin access logs for signs of compromise."
    },
    {
      "item_id": "6c75dee5fc404218",
      "title": "NCSC CEO: Hostile states linked to three-quarters of cyber attacks affecting UK's critical systems",
      "url": "https://www.ncsc.gov.uk/news/ncsc-ceo-hostile-states-linked-to-three-quarters-of-cyber-attacks",
      "priority": "Medium",
      "action": "Use as a lead talking point on nation-state risk for critical-infrastructure and regulated clients."
    },
    {
      "item_id": "d1230fe571401997",
      "title": "Software supply chain attacks: check your dependencies",
      "url": "https://www.ncsc.gov.uk/blogs/software-supply-chain-attacks-check-your-dependencies",
      "priority": "Medium",
      "action": "Advise software clients to inventory and monitor dependencies (SBOM, pinning, provenance) and capture it as supply-chain control evidence."
    },
    {
      "item_id": "395560d6009eee7a",
      "title": "Thinking carefully before adopting agentic AI",
      "url": "https://www.ncsc.gov.uk/blogs/thinking-carefully-before-adopting-agentic-ai",
      "priority": "Medium",
      "action": "Offer clients an agentic-AI readiness and oversight check framed against ISO/IEC 42001 controls before deployment."
    },
    {
      "item_id": "1736b123361f4d57",
      "title": "Executive Summary: Defending against China-nexus covert networks of compromised devices",
      "url": "https://www.ncsc.gov.uk/news/executive-summary-defending-against-china-nexus-covert-networks-of-compromised-devices",
      "priority": "Medium",
      "action": "Recommend clients baseline edge/VPN traffic and add covert-network indicator filtering to their monitoring."
    }
  ],
  "newsletter_candidates": [
    {
      "id": "26bcb636d6619c8f",
      "title": "CRITICAL ALERT: Active exploitation of cPanel/WHM critical vulnerability",
      "source": "ASD ACSC — Alerts & advisories",
      "source_type": "government",
      "published_date": "2026-05-01",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/active-exploitation-of-cpanel-whm-critical-vulnerability",
      "priority": "High",
      "relevance_score": 4,
      "lens": "ASD",
      "summary": "ASD's ACSC reports active exploitation of a critical cPanel/WHM administration vulnerability (CVE-2026-4194). Patches are available and exposed hosting-management consoles are being targeted.",
      "why_it_matters": "A live test of patch-management discipline — Essential Eight 'patch applications' (ML2/ML3 timeframes) and ISM patching controls. Any client on cPanel-based or reseller hosting has an open exposure window now, not a future risk.",
      "suggested_action": "Alert clients running cPanel/WHM, confirm CVE-2026-4194 is patched, and capture the remediation timeline as Essential Eight / ISM control evidence.",
      "newsletter_candidate": true,
      "tags": [
        "acsc",
        "vulnerability"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "78e47568529ad914",
      "title": "Preparing for a ‘vulnerability patch wave’",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-05-01",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/blogs/prepare-for-vulnerability-patch-wave",
      "priority": "High",
      "relevance_score": 4,
      "lens": "CyberResilience",
      "summary": "UK NCSC warns of an incoming 'patch wave' as years of accumulated technical debt are addressed across products, and urges organisations to build patch-management capacity now.",
      "why_it_matters": "Speaks directly to ISO/IEC 27001 Annex A vulnerability- and change-management controls and Essential Eight patch cadence — useful framing for clients whose patch pipelines cannot absorb surge volumes.",
      "suggested_action": "Review clients' patch-management capacity and SLAs against expected surge volumes and flag where ML2 timeframes are unachievable.",
      "newsletter_candidate": true,
      "tags": [
        "vulnerability",
        "patch"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "d0bc636fd27fbc36",
      "title": "Preparing for severe cyber threat: why leaders must act now",
      "source": "UK NCSC — All updates",
      "source_type": "government",
      "published_date": "2026-04-20",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.ncsc.gov.uk/blogs/preparing-for-severe-cyber-threat-why-leaders-must-act-now",
      "priority": "High",
      "relevance_score": 4,
      "lens": "CyberResilience",
      "summary": "UK NCSC leadership calls on organisations to build collective cyber resilience ahead of a more severe threat environment.",
      "why_it_matters": "Board-level resilience messaging that maps to ISO/IEC 27001 leadership commitment (Clause 5) and cyber-governance reporting — good material for a board or risk-committee conversation.",
      "suggested_action": "Use as a prompt to brief client boards on resilience posture and ISMS leadership commitments.",
      "newsletter_candidate": true,
      "tags": [
        "threat",
        "resilience"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    },
    {
      "id": "e96386b842920f36",
      "title": "HIGH ALERT: Ongoing targeting of online code repositories",
      "source": "ASD ACSC — Alerts & advisories",
      "source_type": "government",
      "published_date": "2025-09-19",
      "retrieved_at": "2026-06-26T10:53:29+10:00",
      "url": "https://www.cyber.gov.au/about-us/view-all-content/alerts-and-advisories/ongoing-targeting-of-online-code-repositories",
      "priority": "High",
      "relevance_score": 4,
      "lens": "ASD",
      "summary": "ASD's ACSC reports increased targeting of online code repositories, with threat actors scanning for exposed secrets and credentials.",
      "why_it_matters": "Directly relevant to secure-development, secrets-management and supply-chain controls (ISM; ISO/IEC 27001 Annex A 8.x; SSDF) — a common and easily checkable client weakness.",
      "suggested_action": "Advise clients to scan repositories for exposed secrets and enforce secret-management and access controls on their code platforms.",
      "newsletter_candidate": true,
      "tags": [
        "acsc",
        "threat"
      ],
      "is_new": false,
      "enriched_by": "pro-plan"
    }
  ],
  "source_health": {
    "checked_at": "2026-06-26T10:53:26+10:00",
    "sources": [
      {
        "id": "acsc-alerts",
        "name": "ASD ACSC — Alerts & advisories",
        "tier": 1,
        "source_type": "government",
        "lens": "ASD",
        "status": "ok",
        "detail": "4 items",
        "items": 4
      },
      {
        "id": "ncsc-uk",
        "name": "UK NCSC — All updates",
        "tier": 1,
        "source_type": "government",
        "lens": "CyberResilience",
        "status": "ok",
        "detail": "20 items",
        "items": 20
      },
      {
        "id": "nist-cyber",
        "name": "NIST — Cybersecurity news",
        "tier": 1,
        "source_type": "standard_body",
        "lens": "CyberResilience",
        "status": "ok",
        "detail": "0 items",
        "items": 0
      },
      {
        "id": "cisa-advisories",
        "name": "CISA — Cybersecurity advisories",
        "tier": 1,
        "source_type": "government",
        "lens": "CyberResilience",
        "status": "fail",
        "detail": "<HTTPError 403: 'Forbidden'>",
        "items": 0
      },
      {
        "id": "apra",
        "name": "APRA — News & publications",
        "tier": 1,
        "source_type": "regulator",
        "lens": "Regulation",
        "status": "ok",
        "detail": "10 items",
        "items": 10
      },
      {
        "id": "oaic",
        "name": "OAIC — News & privacy guidance",
        "tier": 1,
        "source_type": "regulator",
        "lens": "Privacy",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "asic",
        "name": "ASIC — Media & guidance",
        "tier": 1,
        "source_type": "regulator",
        "lens": "Regulation",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "accc",
        "name": "ACCC — News",
        "tier": 1,
        "source_type": "regulator",
        "lens": "Regulation",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "acma",
        "name": "ACMA — News & media",
        "tier": 1,
        "source_type": "regulator",
        "lens": "Regulation",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "homeaffairs-ci",
        "name": "Home Affairs — Critical infrastructure / cyber",
        "tier": 1,
        "source_type": "government",
        "lens": "CyberResilience",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "agd-privacy",
        "name": "Attorney-General's Department — Privacy reform",
        "tier": 1,
        "source_type": "government",
        "lens": "Privacy",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "dta-ai",
        "name": "Digital Transformation Agency — AI in government",
        "tier": 1,
        "source_type": "government",
        "lens": "PublicSector",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "finance-ai-assurance",
        "name": "Dept of Finance / DTA — AI assurance framework",
        "tier": 1,
        "source_type": "government",
        "lens": "PublicSector",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "iso-sc27",
        "name": "ISO/IEC JTC 1/SC 27 — Information security",
        "tier": 1,
        "source_type": "standard_body",
        "lens": "SC27",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "iso-sc42",
        "name": "ISO/IEC JTC 1/SC 42 — Artificial intelligence",
        "tier": 1,
        "source_type": "standard_body",
        "lens": "SC42",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "iso-42001",
        "name": "ISO/IEC 42001 — AI management system",
        "tier": 1,
        "source_type": "standard_body",
        "lens": "ISO42000",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "iso-27001",
        "name": "ISO/IEC 27001 — ISMS",
        "tier": 1,
        "source_type": "standard_body",
        "lens": "ISO27000",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "standards-australia",
        "name": "Standards Australia — Updates",
        "tier": 1,
        "source_type": "standard_body",
        "lens": "SC27",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "enisa",
        "name": "ENISA — News & publications",
        "tier": 1,
        "source_type": "government",
        "lens": "CyberResilience",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      },
      {
        "id": "schneier",
        "name": "Schneier on Security",
        "tier": 2,
        "source_type": "research",
        "lens": "CyberResilience",
        "status": "ok",
        "detail": "10 items",
        "items": 10
      },
      {
        "id": "oecd-ai",
        "name": "OECD.AI — Policy observatory",
        "tier": 2,
        "source_type": "research",
        "lens": "ResponsibleAI",
        "status": "manual",
        "detail": "manual source — not auto-fetched",
        "items": 0
      }
    ],
    "summary": {
      "ok": 5,
      "fail": 1,
      "manual": 15,
      "total": 21
    }
  }
};
